In [1]:
import sys
sys.path.append('../') # or just install the module
sys.path.append('../../fuzzy-tools') # or just install the module

In [2]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

n = 50
x = torch.cat([
    torch.arange(0,n)[None],
    torch.arange(0,n)[None],
    torch.arange(0,n)[None],
    torch.arange(0,n)[None],
],dim=0)[...,None]+1
print(x.shape, x[...,0])
onehot = torch.zeros_like(x)[...,0]
onehot[0,:10] = 1
onehot[1,:3] = 1
onehot[2,:1] = 1
print(onehot.shape, onehot)

torch.Size([4, 50, 1]) tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
         37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
         37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
         37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
         37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])
torch.Size([4, 50]) tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,

In [3]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.seq_clean(x, onehot.bool())
print(r.shape, r[...,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 50, 1]) tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  2,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0

In [4]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.seq_avg_pooling(x, onehot.bool())
print(r.shape, r[...,0])
r = seq_utils.seq_sum_pooling(x, onehot.bool())
print(r.shape, r[...,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 1]) tensor([5, 2, 1, 0])
torch.Size([4, 1]) tensor([55,  6,  1,  0])


In [5]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.seq_avg_pooling(x, onehot.bool())
print(r.shape, r[...,0])
r = seq_utils.seq_avg_norm(x, onehot.bool())
for i in range(0,4):
    print(onehot[i,:])
    print(r.shape, r[i,:,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 1]) tensor([5, 2, 1, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
torch.Size([4, 50, 1]) tensor([ 0.2000,  0.4000,  0.6000,  0.8000,  1.0000,  1.2000,  1.4000,  1.6000,
         1.8000,  2.0000,  2.2000,  2.4000,  2.6000,  2.8000,  3.0000,  3.2000,
         3.4000,  3.6000,  3.8000,  4.0000,  4.2000,  4.4000,  4.6000,  4.8000,
         5.0000,  5.2000,  5.4000,  5.6000,  5.8000,  6.0000,  6.2000,  6.4000,
         6.6000,  6.8000,  7.0000,  7.2000,  7.4000,  7.6000,  7.8000,  8.0000,
         8.2000,  8.4000,  8.6000,  8.8000,  9.0000,  9.2000,  9.4000,  9.6000,
         9.8000, 10.0000])
tensor([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       

In [6]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.seq_sum_pooling(x, onehot.bool())
print(r.shape, r[...,0])
r = seq_utils.seq_sum_norm(x, onehot.bool())
for i in range(0,4):
    print(onehot[i,:])
    print(r.shape, r[i,:,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 1]) tensor([55,  6,  1,  0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
torch.Size([4, 50, 1]) tensor([0.0182, 0.0364, 0.0545, 0.0727, 0.0909, 0.1091, 0.1273, 0.1455, 0.1636,
        0.1818, 0.2000, 0.2182, 0.2364, 0.2545, 0.2727, 0.2909, 0.3091, 0.3273,
        0.3455, 0.3636, 0.3818, 0.4000, 0.4182, 0.4364, 0.4545, 0.4727, 0.4909,
        0.5091, 0.5273, 0.5455, 0.5636, 0.5818, 0.6000, 0.6182, 0.6364, 0.6545,
        0.6727, 0.6909, 0.7091, 0.7273, 0.7455, 0.7636, 0.7818, 0.8000, 0.8182,
        0.8364, 0.8545, 0.8727, 0.8909, 0.9091])
tensor([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
torch.Size([4, 50, 1]) tensor([0.1667, 0.3333,

In [7]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

#x = x.to('cuda:3')
#onehot = onehot.to('cuda:3')
#onehot.to()
r = seq_utils.seq_min_pooling(x, onehot.bool())
print(r.shape, r[...,0])
r = seq_utils.seq_max_pooling(x, onehot.bool())
print(r.shape, r[...,0])
r = seq_utils.seq_min_max_norm(x, onehot.bool())
print(r.device)
for i in range(0,4):
    print(onehot[i,:])
    print(r.shape, r[i,:,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 1]) tensor([1, 1, 1, 0])
torch.Size([4, 1]) tensor([10,  3,  1,  0])
cpu
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
torch.Size([4, 50, 1]) tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
to

In [10]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.get_seq_onehot_mask(torch.tensor([5,7,2,1,0]), 10)
print(r.shape, r)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([5, 10]) tensor([[ True,  True,  True,  True,  True, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True, False, False, False],
        [ True,  True, False, False, False, False, False, False, False, False],
        [ True, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])


In [15]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

onehot = torch.zeros_like(x)[...,0]
onehot[0,0] = 1
onehot[0,1] = 1
onehot[0,2] = 1
onehot[0,9] = 1

onehot[1,0] = 1
onehot[1,2] = 1
onehot[1,7] = 1
onehot[1,11] = 1

onehot[2,12] = 1
onehot[2,13] = 1
onehot[2,14] = 1

p = seq_utils.serial_to_parallel(x, onehot.bool())
for i in range(0,len(onehot)):
    print(onehot.shape, onehot[i,:])
    print(p.shape, p[i,:,0])
    print('***')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 50]) tensor([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
torch.Size([4, 50, 1]) tensor([ 1,  2,  3, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])
***
torch.Size([4, 50]) tensor([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
torch.Size([4, 50, 1]) tensor([ 1,  3,  8, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])
***
torch.Size([4, 50]

In [27]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch
import numpy as np

y = torch.clone(x).float()[:2]
y[1] = y[1]+5
y[0,20:,:] = 0
y[1,10:,:] = 0
print(y.shape, y[0,:,0])
print(y.shape, y[1,:,0])
print('***'*10)
y_onehot = seq_utils.get_random_onehot(y, 2)
y_onehot[0,:,:] = 0
y_onehot[1,20:,:] = 0
res = []
for i in range(2):
    p_y_onehot = y_onehot[...,i]
    y_p = seq_utils.serial_to_parallel(y, p_y_onehot)
    print(p_y_onehot.shape, p_y_onehot.int())
    print(y_p.shape, y_p[...,0])
    res.append(y_p)
    print('***'*5)

print('***'*10)
s = seq_utils.parallel_to_serial(res, y_onehot)
print(s.shape, s[0,:,0])
print(s.shape, s[1,:,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([2, 50, 1]) tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
torch.Size([2, 50, 1]) tensor([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
******************************
torch.Size([2, 50]) tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,