In [1]:
import sys
sys.path.append('../') # or just install the module
sys.path.append('../../fuzzy-tools') # or just install the module

In [2]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

n = 20
x = torch.cat([
    torch.arange(0,n)[None],
    torch.arange(0,n)[None],
    torch.arange(0,n)[None],
    torch.arange(0,n)[None],
],dim=0)[...,None]+1
x = x.float()
print(x.shape, x[...,0])
onehot = torch.zeros_like(x)[...,0]
onehot[0,:10] = 1
onehot[1,:] = 1
onehot[2,:1] = 1
print(onehot.shape, onehot)

torch.Size([4, 20, 1]) tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.]])
torch.Size([4, 20]) tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]])


In [3]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.seq_clean(x, onehot.bool(), -1)
print(r.shape, r[...,0])
r = seq_utils.seq_last_element(x, onehot.bool(), empty_seq_value=-1)
print(r.shape, r[...,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 20, 1]) tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.],
        [ 1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1.]])
torch.Size([4, 1]) tensor([10., 20.,  1., -1.])


In [4]:
aa = 0
for k in range(1, 20+1):
    aa += k
    
print(aa/20)

10.5


In [5]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.seq_sum_pooling(x, onehot.bool(), -1)
print(r.shape, r[...,0])
r = seq_utils.seq_avg_pooling(x, onehot.bool(), -1)
print(r.shape, r[...,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 1]) tensor([ 55., 210.,   1.,  -1.])
torch.Size([4, 1]) tensor([ 5.5000, 10.5000,  1.0000, -1.0000])


In [6]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.seq_avg_pooling(x, onehot.bool())
print(r.shape, r[...,0])
r = seq_utils.seq_avg_norm(x, onehot.bool())
for i in range(0,4):
    print(onehot[i,:])
    print(r.shape, r[i,:,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 1]) tensor([ 5.5000, 10.5000,  1.0000,  0.0000])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])
torch.Size([4, 20, 1]) tensor([0.1818, 0.3636, 0.5455, 0.7273, 0.9091, 1.0909, 1.2727, 1.4545, 1.6364,
        1.8182, 2.0000, 2.1818, 2.3636, 2.5454, 2.7273, 2.9091, 3.0909, 3.2727,
        3.4545, 3.6364])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])
torch.Size([4, 20, 1]) tensor([0.0952, 0.1905, 0.2857, 0.3810, 0.4762, 0.5714, 0.6667, 0.7619, 0.8571,
        0.9524, 1.0476, 1.1429, 1.2381, 1.3333, 1.4286, 1.5238, 1.6190, 1.7143,
        1.8095, 1.9048])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])
torch.Size([4, 20, 1]) tensor([ 1.0000,  2.0000,  3.0000,  4.0000,  4.9999,  5.9999,  6.9999,  7.9999,
         8.9999,  9.9999, 10.9999, 11.

In [7]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.seq_sum_pooling(x, onehot.bool())
print(r.shape, r[...,0])
r = seq_utils.seq_sum_norm(x, onehot.bool())
for i in range(0,4):
    print(onehot[i,:])
    print(r.shape, r[i,:,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 1]) tensor([ 55., 210.,   1.,   0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])
torch.Size([4, 20, 1]) tensor([0.0182, 0.0364, 0.0545, 0.0727, 0.0909, 0.1091, 0.1273, 0.1455, 0.1636,
        0.1818, 0.2000, 0.2182, 0.2364, 0.2545, 0.2727, 0.2909, 0.3091, 0.3273,
        0.3455, 0.3636])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])
torch.Size([4, 20, 1]) tensor([0.0048, 0.0095, 0.0143, 0.0190, 0.0238, 0.0286, 0.0333, 0.0381, 0.0429,
        0.0476, 0.0524, 0.0571, 0.0619, 0.0667, 0.0714, 0.0762, 0.0810, 0.0857,
        0.0905, 0.0952])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])
torch.Size([4, 20, 1]) tensor([ 1.0000,  2.0000,  3.0000,  4.0000,  4.9999,  5.9999,  6.9999,  7.9999,
         8.9999,  9.9999, 10.9999, 11.9999, 12.999

In [8]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.seq_min_pooling(x, onehot.bool())
print('r',r.shape, r[...,0])
r = seq_utils.seq_max_pooling(x, onehot.bool())
print('r',r.shape, r[...,0])
r = seq_utils.seq_min_max_norm(x, onehot.bool())
print(r.device)
for i in range(0,4):
    print(onehot[i,:])
    print(r.shape, r[i,:,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
r torch.Size([4, 1]) tensor([1., 1., 1., 0.])
r torch.Size([4, 1]) tensor([10., 20.,  1.,  0.])
cpu
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])
torch.Size([4, 20, 1]) tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])
torch.Size([4, 20, 1]) tensor([0.0000, 0.0526, 0.1053, 0.1579, 0.2105, 0.2632, 0.3158, 0.3684, 0.4211,
        0.4737, 0.5263, 0.5789, 0.6316, 0.6842, 0.7368, 0.7895, 0.8421, 0.8947,
        0.9474, 1.0000])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])
torch.Size([4, 20, 1]) tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
  

In [9]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

r = seq_utils.get_seq_onehot_mask(torch.tensor([5,7,2,1,0]), 10)
print(r.shape, r)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([5, 10]) tensor([[ True,  True,  True,  True,  True, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True, False, False, False],
        [ True,  True, False, False, False, False, False, False, False, False],
        [ True, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])


In [10]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch

onehot = torch.zeros_like(x)[...,0]
onehot[0,0] = 1
onehot[0,1] = 1
onehot[0,2] = 1
onehot[0,9] = 1

onehot[1,0] = 1
onehot[1,2] = 1
onehot[1,7] = 1
onehot[1,11] = 1

onehot[2,12] = 1
onehot[2,13] = 1
onehot[2,14] = 1

p = seq_utils.serial_to_parallel(x, onehot.bool())
for i in range(0,len(onehot)):
    print(onehot.shape, onehot[i,:])
    print(p.shape, p[i,:,0])
    print('***')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([4, 20]) tensor([1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])
torch.Size([4, 20, 1]) tensor([ 1.,  2.,  3., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.])
***
torch.Size([4, 20]) tensor([1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0.])
torch.Size([4, 20, 1]) tensor([ 1.,  3.,  8., 12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.])
***
torch.Size([4, 20]) tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
        0., 0.])
torch.Size([4, 20, 1]) tensor([13., 14., 15.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.])
***
torch.Size([4, 20]) tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([4, 20, 1

In [11]:
%load_ext autoreload
%autoreload 2
import fuzzytorch.models.seq_utils as seq_utils
import torch
import numpy as np

y = torch.clone(x).float()[:2]
y[1] = y[1]+5
y[0,20:,:] = 0
y[1,10:,:] = 0
print(y.shape, y[0,:,0])
print(y.shape, y[1,:,0])
print('***'*10)
y_onehot = seq_utils.get_random_onehot(y, 2)
y_onehot[0,:,:] = 0
y_onehot[1,20:,:] = 0
res = []
for i in range(2):
    p_y_onehot = y_onehot[...,i]
    y_p = seq_utils.serial_to_parallel(y, p_y_onehot)
    print(p_y_onehot.shape, p_y_onehot.int())
    print(y_p.shape, y_p[...,0])
    res.append(y_p)
    print('***'*5)

print('***'*10)
s = seq_utils.parallel_to_serial(res, y_onehot)
print(s.shape, s[0,:,0])
print(s.shape, s[1,:,0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([2, 20, 1]) tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.])
torch.Size([2, 20, 1]) tensor([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.])
******************************
torch.Size([2, 20]) tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1]],
       dtype=torch.int32)
torch.Size([2, 20, 1]) tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 7.,  8.,  9., 12., 13., 15.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.]])
***************
torch.Size([2, 20]) tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0